# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-06 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171103_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新'),
        ),
    ]
